EXEC dbo.usp_world_countries 'AE','United Arab Emirates'
EXEC dbo.usp_world_countries 'AF','Afghanistan'
EXEC dbo.usp_world_countries 'AG','Antigua And Barbuda'
EXEC dbo.usp_world_countries 'AI','Anguilla'
EXEC dbo.usp_world_countries 'AL','Albania'
EXEC dbo.usp_world_countries 'AM','Armenia'
EXEC dbo.usp_world_countries 'AO','Angola'
EXEC dbo.usp_world_countries 'AR','Argentina'
EXEC dbo.usp_world_countries 'AS','American Samoa'
EXEC dbo.usp_world_countries 'AT','Austria'
EXEC dbo.usp_world_countries 'AU','Australia'
EXEC dbo.usp_world_countries 'AW','Aruba'
EXEC dbo.usp_world_countries 'AZ','Azerbaijan'
EXEC dbo.usp_world_countries 'BA','Bosnia And Herzegovina'
EXEC dbo.usp_world_countries 'BB','Barbados'
EXEC dbo.usp_world_countries 'BD','Bangladesh'
EXEC dbo.usp_world_countries 'BE','Belgium'
EXEC dbo.usp_world_countries 'BF','Burkina Faso'
EXEC dbo.usp_world_countries 'BG','Bulgaria'
EXEC dbo.usp_world_countries 'BH','Bahrain'
EXEC dbo.usp_world_countries 'BI','Burundi'
EXEC dbo.usp_world_countries 'BJ','Benin'
EXEC dbo.usp_world_countries 'BM','Bermuda'
EXEC dbo.usp_world_countries 'BN','Brunei'
EXEC dbo.usp_world_countries 'BO','Bolivia'
EXEC dbo.usp_world_countries 'BQ','Bes Islands'
EXEC dbo.usp_world_countries 'BR','Brazil'
EXEC dbo.usp_world_countries 'BS','Bahamas'
EXEC dbo.usp_world_countries 'BT','Bhutan'
EXEC dbo.usp_world_countries 'BW','Botswana'
EXEC dbo.usp_world_countries 'BY','Belarus'
EXEC dbo.usp_world_countries 'BZ','Belize'
EXEC dbo.usp_world_countries 'CA','Canada'
EXEC dbo.usp_world_countries 'CC','Cocos (keeling) Islands'
EXEC dbo.usp_world_countries 'CD','Congo (kinshasa)'
EXEC dbo.usp_world_countries 'CF','Central African Republic'
EXEC dbo.usp_world_countries 'CG','Congo (brazzaville)'
EXEC dbo.usp_world_countries 'CH','Switzerland'
EXEC dbo.usp_world_countries 'CI','Ivory Coast'
EXEC dbo.usp_world_countries 'CK','Cook Islands'
EXEC dbo.usp_world_countries 'CL','Chile'
EXEC dbo.usp_world_countries 'CM','Cameroon'
EXEC dbo.usp_world_countries 'CN','China'
EXEC dbo.usp_world_countries 'CO','Colombia'
EXEC dbo.usp_world_countries 'CR','Costa Rica'
EXEC dbo.usp_world_countries 'CU','Cuba'
EXEC dbo.usp_world_countries 'CV','Cape Verde'
EXEC dbo.usp_world_countries 'CW','Curacao'
EXEC dbo.usp_world_countries 'CX','Christmas Island'
EXEC dbo.usp_world_countries 'CY','Cyprus'
EXEC dbo.usp_world_countries 'CZ','Czech Republic'
EXEC dbo.usp_world_countries 'DE','Germany'
EXEC dbo.usp_world_countries 'DJ','Djibouti'
EXEC dbo.usp_world_countries 'DK','Denmark'
EXEC dbo.usp_world_countries 'DM','Dominica'
EXEC dbo.usp_world_countries 'DO','Dominican Republic'
EXEC dbo.usp_world_countries 'DZ','Algeria'
EXEC dbo.usp_world_countries 'EC','Ecuador'
EXEC dbo.usp_world_countries 'EE','Estonia'
EXEC dbo.usp_world_countries 'EG','Egypt'
EXEC dbo.usp_world_countries 'ER','Eritrea'
EXEC dbo.usp_world_countries 'ES','Spain'
EXEC dbo.usp_world_countries 'ET','Ethiopia'
EXEC dbo.usp_world_countries 'FI','Finland'
EXEC dbo.usp_world_countries 'FJ','Fiji'
EXEC dbo.usp_world_countries 'FK','Falkland Islands'
EXEC dbo.usp_world_countries 'FM','Micronesia'
EXEC dbo.usp_world_countries 'FO','Faroe Islands'
EXEC dbo.usp_world_countries 'FR','France'
EXEC dbo.usp_world_countries 'GA','Gabon'
EXEC dbo.usp_world_countries 'GB','United Kingdom'
EXEC dbo.usp_world_countries 'GD','Grenada'
EXEC dbo.usp_world_countries 'GE','Georgia'
EXEC dbo.usp_world_countries 'GF','French Guiana'
EXEC dbo.usp_world_countries 'GH','Ghana'
EXEC dbo.usp_world_countries 'GI','Gibraltar'
EXEC dbo.usp_world_countries 'GL','Greenland'
EXEC dbo.usp_world_countries 'GM','Gambia'
EXEC dbo.usp_world_countries 'GN','Guinea'
EXEC dbo.usp_world_countries 'GP','Guadeloupe'
EXEC dbo.usp_world_countries 'GQ','Equatorial Guinea'
EXEC dbo.usp_world_countries 'GR','Greece'
EXEC dbo.usp_world_countries 'GT','Guatemala'
EXEC dbo.usp_world_countries 'GU','Guam'
EXEC dbo.usp_world_countries 'GW','Guinea-Bissau'
EXEC dbo.usp_world_countries 'GY','Guyana'
EXEC dbo.usp_world_countries 'HK','Hong Kong'
EXEC dbo.usp_world_countries 'HN','Honduras'
EXEC dbo.usp_world_countries 'HR','Croatia'
EXEC dbo.usp_world_countries 'HT','Haiti'
EXEC dbo.usp_world_countries 'HU','Hungary'
EXEC dbo.usp_world_countries 'ID','Indonesia'
EXEC dbo.usp_world_countries 'IE','Ireland'
EXEC dbo.usp_world_countries 'IL','Israel'
EXEC dbo.usp_world_countries 'IN','India'
EXEC dbo.usp_world_countries 'IQ','Iraq'
EXEC dbo.usp_world_countries 'IR','Iran'
EXEC dbo.usp_world_countries 'IS','Iceland'
EXEC dbo.usp_world_countries 'IT','Italy'
EXEC dbo.usp_world_countries 'JM','Jamaica'
EXEC dbo.usp_world_countries 'JO','Jordan'
EXEC dbo.usp_world_countries 'JP','Japan'
EXEC dbo.usp_world_countries 'KE','Kenya'
EXEC dbo.usp_world_countries 'KG','Kyrgyzstan'
EXEC dbo.usp_world_countries 'KH','Cambodia'
EXEC dbo.usp_world_countries 'KI','Kiribati'
EXEC dbo.usp_world_countries 'KM','Comoros'
EXEC dbo.usp_world_countries 'KN','Saint Kitts And Nevis'
EXEC dbo.usp_world_countries 'KP','North Korea'
EXEC dbo.usp_world_countries 'KR','South Korea'
EXEC dbo.usp_world_countries 'KW','Kuwait'
EXEC dbo.usp_world_countries 'KY','Cayman Islands'
EXEC dbo.usp_world_countries 'KZ','Kazakhstan'
EXEC dbo.usp_world_countries 'LA','Laos'
EXEC dbo.usp_world_countries 'LB','Lebanon'
EXEC dbo.usp_world_countries 'LC','Saint Lucia'
EXEC dbo.usp_world_countries 'LK','Sri Lanka'
EXEC dbo.usp_world_countries 'LR','Liberia'
EXEC dbo.usp_world_countries 'LS','Lesotho'
EXEC dbo.usp_world_countries 'LT','Lithuania'
EXEC dbo.usp_world_countries 'LU','Luxembourg'
EXEC dbo.usp_world_countries 'LV','Latvia'
EXEC dbo.usp_world_countries 'LY','Libya'
EXEC dbo.usp_world_countries 'MA','Morocco'
EXEC dbo.usp_world_countries 'MC','Monaco'
EXEC dbo.usp_world_countries 'MD','Moldova'
EXEC dbo.usp_world_countries 'ME','Montenegro'
EXEC dbo.usp_world_countries 'MG','Madagascar'
EXEC dbo.usp_world_countries 'MH','Marshall Islands'
EXEC dbo.usp_world_countries 'MK','Macedonia'
EXEC dbo.usp_world_countries 'ML','Mali'
EXEC dbo.usp_world_countries 'MM','Myanmar'
EXEC dbo.usp_world_countries 'MN','Mongolia'
EXEC dbo.usp_world_countries 'MO','Macau'
EXEC dbo.usp_world_countries 'MP','Mariana Islands'
EXEC dbo.usp_world_countries 'MQ','Martinique'
EXEC dbo.usp_world_countries 'MR','Mauritania'
EXEC dbo.usp_world_countries 'MT','Malta'
EXEC dbo.usp_world_countries 'MU','Mauritius'
EXEC dbo.usp_world_countries 'MV','Maldives'
EXEC dbo.usp_world_countries 'MW','Malawi'
EXEC dbo.usp_world_countries 'MX','Mexico'
EXEC dbo.usp_world_countries 'MY','Malaysia'
EXEC dbo.usp_world_countries 'MZ','Mozambique'
EXEC dbo.usp_world_countries 'NA','Namibia'
EXEC dbo.usp_world_countries 'NC','New Caledonia'
EXEC dbo.usp_world_countries 'NE','Niger'
EXEC dbo.usp_world_countries 'NF','Norfolk Island'
EXEC dbo.usp_world_countries 'NG','Nigeria'
EXEC dbo.usp_world_countries 'NI','Nicaragua'
EXEC dbo.usp_world_countries 'NL','Netherlands'
EXEC dbo.usp_world_countries 'NO','Norway'
EXEC dbo.usp_world_countries 'NP','Nepal'
EXEC dbo.usp_world_countries 'NR','Nauru'
EXEC dbo.usp_world_countries 'NU','Niue'
EXEC dbo.usp_world_countries 'NZ','New Zealand'
EXEC dbo.usp_world_countries 'OM','Oman'
EXEC dbo.usp_world_countries 'PA','Panama'
EXEC dbo.usp_world_countries 'PE','Peru'
EXEC dbo.usp_world_countries 'PF','French Polynesia'
EXEC dbo.usp_world_countries 'PG','Papua New Guinea'
EXEC dbo.usp_world_countries 'PH','Philippines'
EXEC dbo.usp_world_countries 'PK','Pakistan'
EXEC dbo.usp_world_countries 'PL','Poland'
EXEC dbo.usp_world_countries 'PM','Saint Pierre And Miquelon'
EXEC dbo.usp_world_countries 'PR','Puerto Rico'
EXEC dbo.usp_world_countries 'PT','Portugal'
EXEC dbo.usp_world_countries 'PW','Palau'
EXEC dbo.usp_world_countries 'PY','Paraguay'
EXEC dbo.usp_world_countries 'QA','Qatar'
EXEC dbo.usp_world_countries 'RE','Reunion'
EXEC dbo.usp_world_countries 'RO','Romania'
EXEC dbo.usp_world_countries 'RS','Serbia'
EXEC dbo.usp_world_countries 'RU','Russia'
EXEC dbo.usp_world_countries 'RW','Rwanda'
EXEC dbo.usp_world_countries 'SA','Saudi Arabia'
EXEC dbo.usp_world_countries 'SB','Solomon Islands'
EXEC dbo.usp_world_countries 'SC','Seychelles'
EXEC dbo.usp_world_countries 'SD','Sudan'
EXEC dbo.usp_world_countries 'SE','Sweden'
EXEC dbo.usp_world_countries 'SG','Singapore'
EXEC dbo.usp_world_countries 'SH','Saint Helena'
EXEC dbo.usp_world_countries 'SI','Slovenia'
EXEC dbo.usp_world_countries 'SJ','Svalbard And Jan Mayen'
EXEC dbo.usp_world_countries 'SK','Slovakia'
EXEC dbo.usp_world_countries 'SL','Sierra Leone'
EXEC dbo.usp_world_countries 'SN','Senegal'
EXEC dbo.usp_world_countries 'SO','Somalia'
EXEC dbo.usp_world_countries 'SR','Suriname'
EXEC dbo.usp_world_countries 'ST','Sao Tome And Principe'
EXEC dbo.usp_world_countries 'SV','El Salvador'
EXEC dbo.usp_world_countries 'SX','Sint Maarten'
EXEC dbo.usp_world_countries 'SY','Syrian Arab Republic'
EXEC dbo.usp_world_countries 'SZ','Swaziland'
EXEC dbo.usp_world_countries 'TC','Turks And Caicos Islands'
EXEC dbo.usp_world_countries 'TD','Chad'
EXEC dbo.usp_world_countries 'TG','Togo'
EXEC dbo.usp_world_countries 'TH','Thailand'
EXEC dbo.usp_world_countries 'TJ','Tajikistan'
EXEC dbo.usp_world_countries 'TL','East Timor'
EXEC dbo.usp_world_countries 'TM','Turkmenistan'
EXEC dbo.usp_world_countries 'TN','Tunisia'
EXEC dbo.usp_world_countries 'TO','Tonga'
EXEC dbo.usp_world_countries 'TR','Turkey'
EXEC dbo.usp_world_countries 'TT','Trinidad And Tobago'
EXEC dbo.usp_world_countries 'TV','Tuvalu'
EXEC dbo.usp_world_countries 'TW','Taiwan'
EXEC dbo.usp_world_countries 'TZ','Tanzania'
EXEC dbo.usp_world_countries 'UA','Ukraine'
EXEC dbo.usp_world_countries 'UG','Uganda'
EXEC dbo.usp_world_countries 'US','United States'
EXEC dbo.usp_world_countries 'UY','Uruguay'
EXEC dbo.usp_world_countries 'UZ','Uzbekistan'
EXEC dbo.usp_world_countries 'VC','Saint Vincent And The Grenadines'
EXEC dbo.usp_world_countries 'VE','Venezuela'
EXEC dbo.usp_world_countries 'VG','Virgin Islands, British'
EXEC dbo.usp_world_countries 'VI','Virgin Islands, U.S.'
EXEC dbo.usp_world_countries 'VN','Vietnam'
EXEC dbo.usp_world_countries 'VU','Vanuatu'
EXEC dbo.usp_world_countries 'WF','Wallis And Futuna'
EXEC dbo.usp_world_countries 'WS','Samoa'
EXEC dbo.usp_world_countries 'YE','Yemen'
EXEC dbo.usp_world_countries 'YT','Mayotte'
EXEC dbo.usp_world_countries 'ZA','South Africa'
EXEC dbo.usp_world_countries 'ZM','Zambia'
EXEC dbo.usp_world_countries 'ZW','Zimbabwe'